#!/usr/bin/env node

/**
 * generate-latex.mjs — Validate and compile a generated .tex CV file to PDF
 *
 * Usage:
 *   node generate-latex.mjs <input.tex> [output.pdf]
 *   node generate-latex.mjs <input.tex> [output.pdf] --compile-only
 *
 * --compile-only: skip template validation; compile any user-owned .tex (latex-tex mode).
 *
 * Reads the .tex file, validates structure, compiles to PDF via tectonic, xelatex, or pdflatex.
 * If output.pdf is omitted, writes to the same directory as input with .pdf extension.
 * The .tex file is generated by the AI agent using templates-fork/cv-template.tex.
 *
 * Requires: tectonic (preferred, brew install tectonic), xelatex (for OpenType fonts like Figtree),
 *           or pdflatex (MiKTeX / TeX Live) on PATH.
 */

import { readFile, writeFile, stat, copyFile, rm } from 'fs/promises';
import { resolve, basename, dirname, join } from 'path';
import { execFileSync } from 'child_process';
import { existsSync, mkdirSync } from 'fs';
import { getCareerOpsRoot } from './path-resolver.mjs';
import { isMainModule } from './lib/is-main-module.mjs';

// User-layer files (cv.md, config/profile.yml, reports/) live under the data root,
// which CAREER_OPS_DATA_DIR / .career-ops-data can move out of the repo.
const DATA_ROOT = getCareerOpsRoot();

// CV language (--lang=). cv.md stays the source of truth for WHICH entries and
// bullets are printed (the report's selectors point into it); the language file
// supplies the text at the same position, so it must mirror cv.md entry by entry.
const CV_FILES = { en: 'cv.md', it: 'cv.it.md' };
const SECTION_TITLES = {
  it: { Summary: 'Profilo', Projects: 'Progetti', Experience: 'Esperienza', 'Technical Skills': 'Competenze Tecniche', Education: 'Formazione', Certifications: 'Certificazioni' },
};
const BABEL = { en: 'english', it: 'italian' };
const COUNTRY = { it: { Italy: 'Italia' } };

// ponytail: stopword count. Enough to tell an Italian CV paragraph from an
// English one; a third language needs a real detector.
const STOPWORDS = {
  it: ['di', 'e', 'il', 'la', 'le', 'che', 'per', 'con', 'un', 'una', 'del', 'della', 'nel', 'nella', 'su', 'sul', 'da', 'non'],
  en: ['the', 'and', 'of', 'with', 'to', 'for', 'on', 'across', 'from', 'by', 'is', 'that'],
};
export function guessLanguage(text) {
  const words = String(text).toLowerCase().match(/[a-zàèéìòù]+/g) || [];
  const count = l => words.filter(w => STOPWORDS[l].includes(w)).length;
  return count('it') > count('en') ? 'it' : 'en';
}

// The language file must have the same entries and bullet counts as cv.md,
// in the same order, or a report selector would print the wrong bullet.
export function checkParity(en, out, countOf, section, file, issues) {
  if (en === out) return;
  if (en.length !== out.length) {
    issues.push(`${file}: ${section} has ${out.length} entries, cv.md has ${en.length}`);
    return;
  }
  en.forEach((e, i) => {
    if (countOf(e) !== countOf(out[i])) {
      issues.push(`${file}: ${section} entry ${i + 1} has ${countOf(out[i])} bullets, cv.md has ${countOf(e)}`);
    }
  });
}

// Escape plain text for safe insertion into a LaTeX document.
// Order matters: backslash first, then the rest.
function escapeLatex(s) {
  return String(s)
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

// Extract the body of a Markdown H2 section. Stops at the next H2 or EOF.
function extractMarkdownSection(md, headingRegex) {
  const m = md.match(headingRegex);
  if (!m) return null;
  const start = m.index + m[0].length;
  const rest = md.slice(start);
  const nextHeading = rest.match(/\n##\s/);
  const end = nextHeading ? nextHeading.index : rest.length;
  const body = rest.slice(0, end).trim();
  return body || null;
}

// Return the first plain-text paragraph from a section body, skipping bullets,
// code fences, tables and HTML-comment lines.
function firstParagraph(body) {
  if (!body) return null;
  for (const p of body.split(/\n\s*\n/)) {
    const t = p.trim();
    if (!t) continue;
    if (/^[-*+]\s/.test(t) || /^```/.test(t) || /^\|/.test(t) || /^<!--/.test(t)) continue;
    return t.replace(/\n+/g, ' ').replace(/\s+/g, ' ');
  }
  return null;
}

// Source chain: report "## Tailored CV Summary (<lang>)" > report
// "## Tailored CV Summary" if it is written in <lang> > the CV file's Summary.
async function extractTailoredSummary({ scriptDir, reportFlag, lang, cvFile }) {
  let skipped = '';
  if (reportFlag) {
    try {
      const md = await readFile(resolve(reportFlag), 'utf-8');
      const tagged = firstParagraph(extractMarkdownSection(md, new RegExp(`^##\\s+Tailored CV Summary \\(${lang}\\)\\s*$`, 'm')));
      if (tagged) return { text: tagged, source: `report:${reportFlag}:${lang}` };
      const plain = firstParagraph(extractMarkdownSection(md, /^##\s+Tailored CV Summary\s*$/m)
        || extractMarkdownSection(md, /^##\s+Summary\s*$/m));
      if (plain && guessLanguage(plain) === lang) return { text: plain, source: `report:${reportFlag}` };
      if (plain) skipped = ` (report summary is not in ${lang})`;
    } catch { /* fall through */ }
  }

  // No --report: use cv.md. Guessing "the most recent report" put another
  // offer's summary (in another language) into the CV.
  try {
    const md = await readFile(resolve(scriptDir, cvFile), 'utf-8');
    const body = extractMarkdownSection(md, /^##\s+Summary\s*$/m);
    const text = firstParagraph(body);
    if (text) return { text, source: cvFile + skipped };
  } catch { /* nothing */ }

  return null;
}

// Extract certification bullets from cv.md "## Certifications" section.
// Returns array of raw strings (one per bullet). Empty array if section is
// missing, empty, or contains no "- item" lines.
function extractCertifications(md) {
  const body = extractMarkdownSection(md, /^##\s+Certifications\s*$/m);
  if (!body) return [];
  const bullets = [];
  for (const line of body.split('\n')) {
    const m = line.match(/^\s*-\s+(.+?)\s*$/);
    if (m) bullets.push(m[1]);
  }
  return bullets;
}

// Format certifications as middot-separated LaTeX one-liner (regular weight).
// Empty array returns empty string (section renders title-only, per user spec).
function formatCertificationsLatex(certs) {
  if (!certs.length) return '';
  return certs
    .map(c => escapeLatex(c))
    .join(' \\enspace$\\cdot$\\enspace ');
}

// Parse the CONTACT_LINE parts from profile.yml (identity block only).
// Returns assembled LaTeX "phone $|$ city, country" (values LaTeX-escaped,
// separator left raw as math-mode bar) or null if no fields available.
// Visa status is intentionally excluded — it's an internal field for
// sponsorship checks in oferta mode, not a CV-public field.
function parseContactLine(yml) {
  const identityMatch = yml.match(/^identity:\s*\n([\s\S]*?)(?=\n[a-zA-Z_]+:)/m);
  const identity = identityMatch ? identityMatch[1] : yml;
  const grab = (re) => identity.match(re)?.[1]?.trim();
  const phone = grab(/^\s+phone:\s*["']?([^"'\n]+?)["']?\s*$/m);
  const city = grab(/^\s+city:\s*["']?([^"'\n]+?)["']?\s*$/m);
  const country = grab(/^\s+country:\s*["']?([^"'\n]+?)["']?\s*$/m);
  const parts = [];
  if (phone) parts.push(escapeLatex(phone));
  const loc = [city, country].filter(Boolean).map(escapeLatex).join(', ');
  if (loc) parts.push(loc);
  return parts.length ? parts.join(' $|$ ') : null;
}

// Parse identity block from profile.yml for header placeholders.
// Returns { name, email, linkedin, github } with raw values (URLs unmodified).
// linkedin/github live under identity.links.* in profile.yml; we match by
// indented key inside the identity block, agnostic to nesting depth.
function parseHeaderIdentity(yml) {
  const identityMatch = yml.match(/^identity:\s*\n([\s\S]*?)(?=\n[a-zA-Z_]+:)/m);
  const identity = identityMatch ? identityMatch[1] : yml;
  const grab = (re) => identity.match(re)?.[1]?.trim() || '';
  return {
    name: grab(/^\s+name:\s*["']?([^"'\n]+?)["']?\s*$/m),
    email: grab(/^\s+email:\s*["']?([^"'\n]+?)["']?\s*$/m),
    linkedin: grab(/^\s+linkedin:\s*["']?([^"'\n]+?)["']?\s*$/m),
    github: grab(/^\s+github:\s*["']?([^"'\n]+?)["']?\s*$/m),
  };
}

// Strip protocol, www., and trailing slashes from a URL for display text.
// Empty input returns empty string.
function urlToDisplay(url) {
  if (!url) return '';
  return String(url).replace(/^https?:\/\//, '').replace(/^www\./, '').replace(/\/+$/, '');
}

// ---- SKILLS (from cv.md "## Technical Skills") ----
function extractSkills(md) {
  const body = extractMarkdownSection(md, /^##\s+Technical Skills\s*$/m);
  if (!body) return [];
  const skills = [];
  for (const line of body.split('\n')) {
    const m = line.match(/^\s*-\s+\*\*([^:*]+):\*\*\s*(.+?)\s*$/);
    if (m) skills.push({ category: m[1].trim(), items: m[2].trim() });
  }
  return skills;
}

function formatSkillsLatex(skills) {
  if (!skills.length) return '';
  return skills
    .map((s, i) => {
      const line = `    \\textbf{${escapeLatex(s.category)}}{: ${escapeLatex(s.items)}}`;
      return i < skills.length - 1 ? `${line} \\\\` : line;
    })
    .join('\n');
}

// ---- EDUCATION (from cv.md "## Education") ----
function extractEducation(md) {
  const body = extractMarkdownSection(md, /^##\s+Education\s*$/m);
  if (!body) return [];
  const entries = [];
  const chunks = body.split(/\n(?=###\s)/);
  for (const chunk of chunks) {
    const headingMatch = chunk.match(/^###\s+(.+?)\s*$/m);
    if (!headingMatch) continue;
    const degree = headingMatch[1].trim();
    const grab = (re) => chunk.match(re)?.[1]?.trim() || '';
    entries.push({
      degree,
      institution: grab(/^\*\*Institution:\*\*\s*(.+?)\s*$/m),
      location: grab(/^\*\*Location:\*\*\s*(.+?)\s*$/m),
      dates: grab(/^\*\*Dates:\*\*\s*(.+?)\s*$/m),
    });
  }
  return entries;
}

function formatEducationLatex(entries) {
  if (!entries.length) return '';
  return entries
    .map(e => (
      `    \\resumeSubheading\n` +
      `      {${escapeLatex(e.institution)}}{${escapeLatex(e.dates)}}\n` +
      `      {${escapeLatex(e.degree)}}{${escapeLatex(e.location)}}`
    ))
    .join('\n\n');
}

// ---- RELEVANCE SELECTION (from report "## Relevance Selection (for CV generation)") ----
function normalizeForMatch(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

export function extractRelevanceSelection(md) {
  const result = { experience: [], projects: [] };
  if (!md) return result;
  const rsBody = extractMarkdownSection(md, /^##\s+Relevance Selection.*$/m);
  if (!rsBody) return result;

  const parseSubsection = (headingRe) => {
    const m = rsBody.match(headingRe);
    if (!m) return [];
    const after = rsBody.slice(m.index + m[0].length);
    const nextH3 = after.match(/\n###\s/);
    const subBody = nextH3 ? after.slice(0, nextH3.index) : after;
    const entries = [];
    for (const line of subBody.split('\n')) {
      const lm = line.match(/^\s*\d+\.\s+(.+?)\s+\((primary|secondary|excluded)\)/);
      if (lm) { entries.push({ name: lm[1].trim(), tag: lm[2], order: entries.length }); continue; }
      // Optional, indented under an entry: "   bullets: Scope | Design decisions"
      const bl = line.match(/^\s+bullets:\s*(.+?)\s*$/i);
      if (bl && entries.length) entries[entries.length - 1].bullets = bl[1].split('|').map(b => b.trim()).filter(Boolean);
    }
    return entries;
  };

  result.experience = parseSubsection(/^###\s+Experience\s*$/m);
  result.projects = parseSubsection(/^###\s+Projects\s*$/m);
  return result;
}

// Apply selection: included (primary+secondary) in report order, then cv.md
// entries NOT mentioned as safety-net fallback at tail. Excluded-tagged
// entries are skipped entirely.
function applySelection(cvEntries, selectionList, getName) {
  if (!selectionList.length) {
    return { ordered: cvEntries, info: { selected: 0, fallback: cvEntries.length } };
  }
  const findCvEntry = (selName) => {
    const sn = normalizeForMatch(selName);
    return cvEntries.find(e => {
      const en = normalizeForMatch(getName(e));
      return en.includes(sn) || sn.includes(en);
    });
  };

  const ordered = [];
  const matched = new Set();
  const excludedSet = new Set();

  for (const sel of selectionList) {
    const entry = findCvEntry(sel.name);
    if (!entry) continue;
    if (sel.tag === 'excluded') {
      excludedSet.add(entry);
    } else if (!matched.has(entry)) {
      ordered.push(sel.bullets ? { ...entry, pick: sel.bullets } : entry);
      matched.add(entry);
    }
  }
  const selectedCount = ordered.length;

  let fallback = 0;
  for (const entry of cvEntries) {
    if (!matched.has(entry) && !excludedSet.has(entry)) {
      ordered.push(entry);
      matched.add(entry);
      fallback++;
    }
  }

  return { ordered, info: { selected: selectedCount, fallback } };
}

// Bullets the report picked for one entry, in the report's order. A selector
// matches the start of the bullet text (projects: its bold key), ignoring case
// and punctuation. No selectors: the first `max` in cv.md order. A selector
// that matches nothing is an issue, so a typo in the report stops the build
// instead of silently dropping a bullet.
export function pickBullets(items, selectors, textOf, max, label, issues) {
  if (!selectors || !selectors.length) return items.slice(0, max);
  const picked = [];
  for (const sel of selectors) {
    const want = normalizeForMatch(sel);
    const hit = items.find(i => !picked.includes(i) && normalizeForMatch(textOf(i)).startsWith(want));
    if (hit) picked.push(hit);
    else issues.push(`Relevance Selection: bullet "${sel}" not found in "${label}"`);
  }
  if (picked.length > max) issues.push(`Relevance Selection: "${label}" picks ${picked.length} bullets, max ${max}`);
  return picked.slice(0, max);
}

// Load report markdown for selection parsing: explicit --report > auto-detect most recent.
async function loadReportForSelection({ scriptDir, reportFlag }) {
  if (reportFlag) {
    try { return await readFile(resolve(reportFlag), 'utf-8'); } catch { /* fall through */ }
  }
  // No --report: keep cv.md order rather than another offer's selection.
  return null;
}

// ---- EXPERIENCE (from cv.md "## Experience") ----
function extractExperience(md) {
  const body = extractMarkdownSection(md, /^##\s+Experience\s*$/m);
  if (!body) return [];
  const entries = [];
  const chunks = body.split(/\n(?=###\s)/);
  for (const chunk of chunks) {
    const headingMatch = chunk.match(/^###\s+(.+?)\s*$/m);
    if (!headingMatch) continue;
    const role = headingMatch[1].trim();
    const grab = (re) => chunk.match(re)?.[1]?.trim() || '';
    const bullets = [];
    for (const line of chunk.split('\n')) {
      const bm = line.match(/^-\s+(.+?)\s*$/);
      if (bm) bullets.push(bm[1].trim());
    }
    entries.push({
      role,
      company: grab(/^\*\*Company:\*\*\s*(.+?)\s*$/m),
      location: grab(/^\*\*Location:\*\*\s*(.+?)\s*$/m),
      dates: grab(/^\*\*Dates:\*\*\s*(.+?)\s*$/m),
      bullets,
    });
  }
  return entries;
}

function formatExperienceLatex(entries) {
  if (!entries.length) return '';
  return entries
    .map(e => {
      const items = e.bullets.map(b => `        \\resumeItem{${escapeLatex(b)}}`).join('\n');
      return (
        `    \\resumeSubheading\n` +
        `      {${escapeLatex(e.role)}}{${escapeLatex(e.dates)}}\n` +
        `      {${escapeLatex(e.company)}}{${escapeLatex(e.location)}}\n` +
        `      \\resumeItemListStart\n` +
        items + '\n' +
        `      \\resumeItemListEnd`
      );
    })
    .join('\n\n');
}

// ---- PROJECTS (from cv.md "## Projects") — Opzione D link placement ----
function extractProjects(md) {
  const body = extractMarkdownSection(md, /^##\s+Projects\s*$/m);
  if (!body) return [];
  const entries = [];
  const chunks = body.split(/\n(?=###\s)/);
  for (const chunk of chunks) {
    const headingMatch = chunk.match(/^###\s+(.+?)\s*$/m);
    if (!headingMatch) continue;
    const titleRaw = headingMatch[1].trim();
    let name = titleRaw, descriptor = '';
    const emDashSplit = titleRaw.split(/\s+—\s+/);
    if (emDashSplit.length >= 2) {
      name = emDashSplit[0].trim();
      descriptor = emDashSplit.slice(1).join(' — ').trim();
    }
    const grab = (re) => chunk.match(re)?.[1]?.trim() || '';
    const recognition = grab(/^\*\*Recognition:\*\*\s*(.+?)\s*$/m);
    const date = grab(/^\*\*Date:\*\*\s*(.+?)\s*$/m);
    const linkLine = grab(/^\*\*Link:\*\*\s*(.+?)\s*$/m);
    const link = linkLine ? linkLine.split(/\s+—\s+|\s+/)[0] : '';

    // Description: first non-metadata, non-bullet, non-blank paragraph
    let description = '';
    const lines = chunk.split('\n');
    for (let i = 0; i < lines.length; i++) {
      const l = lines[i].trim();
      if (!l || l.startsWith('###') || l.match(/^\*\*[^:*]+:\*\*/) || l.startsWith('-')) continue;
      description = l;
      let j = i + 1;
      while (j < lines.length) {
        const nl = lines[j].trim();
        if (!nl || nl.startsWith('-') || nl.match(/^\*\*[^:*]+:\*\*/)) break;
        description += ' ' + nl;
        j++;
      }
      break;
    }

    const metaBullets = [];
    for (const line of chunk.split('\n')) {
      const bm = line.match(/^\s*-\s+\*\*([^:*]+):\*\*\s*(.+?)\s*$/);
      if (bm) metaBullets.push({ key: bm[1].trim(), value: bm[2].trim() });
    }

    entries.push({ name, descriptor, recognition, date, link, description, metaBullets });
  }
  return entries;
}

// Length caps. Bullets are taken in cv.md order, so the order there is the
// priority: put the strongest bullet first. The report decides WHICH entries
// and in what order; these caps decide HOW MUCH of each one is printed.
const MAX_PROJECTS = 3;
const MAX_PROJECT_BULLETS = 2;     // after the one-line description
const MAX_EXPERIENCE_BULLETS = 3;

function formatProjectsLatex(entries) {
  if (!entries.length) return '';
  return entries
    .map(p => {
      let titleContent = escapeLatex(p.name);
      if (p.descriptor) titleContent += ` \\emph{$|$ ${escapeLatex(p.descriptor)}}`;
      const title = p.link
        ? `{\\color{BrandAccent}\\faGithub}\\ \\href{${p.link}}{${titleContent}}`
        : titleContent;
      const badge = escapeLatex(p.recognition || p.date || '');
      const items = [];
      if (p.description) items.push(`        \\resumeItem{${escapeLatex(p.description)}}`);
      for (const mb of p.metaBullets) {
        items.push(`        \\resumeItem{\\textbf{${escapeLatex(mb.key)}:} ${escapeLatex(mb.value)}}`);
      }
      return (
        `    \\resumeProjectHeading{${title}}{${badge}}\n` +
        `    \\resumeItemListStart\n` +
        items.join('\n') + '\n' +
        `    \\resumeItemListEnd`
      );
    })
    .join('\n\n');
}

// Sections are counted, not matched by name, so a CV in any language validates
// (Formazione/Esperienza, Educación/Experiencia, ...) — same rule as upstream.
const MIN_SECTIONS = 4;

const REQUIRED_COMMANDS = [
  '\\\\resumeSubheading',
  '\\\\resumeItem',
  '\\\\resumeProjectHeading',
];

// Unicode script test so supplementary-plane ideographs (U+20000+) are caught too.
const CJK_RE = /\p{Script=Han}|\p{Script=Hiragana}|\p{Script=Katakana}|\p{Script=Hangul}/u;

// xeCJK/ctex anywhere in a \usepackage list, or a ctex document class.
const CJK_PACKAGE_RE = /\\usepackage(?:\[[^\]]*\])?\{[^}]*\b(?:xeCJK|ctex)\b[^}]*\}|\\documentclass(?:\[[^\]]*\])?\{ctex(?:art|rep|book)?\}/;

// Prefer tectonic (self-contained), then xelatex (OpenType fonts like Figtree),
// then pdflatex (legacy, no CJK).
export function resolveLatexEngine() {
  for (const candidate of ['tectonic', 'xelatex', 'pdflatex']) {
    try {
      execFileSync(candidate, ['--version'], { stdio: 'pipe' });
      return candidate;
    } catch { /* not found */ }
  }
  return null;
}

/**
 * Structural checks on the fully-substituted .tex.
 * compileOnly (latex-tex mode, user-owned .tex): only document begin/end are
 * checked — the template's sections/commands/placeholders are not required.
 * @param {string} content
 * @param {boolean} compileOnly
 * @param {string|null} [engine] - 'tectonic'/'xelatex'/'pdflatex'/null; affects CJK handling
 * @returns {{ issues: string[], counts: object }}
 */
export function validateLatexContent(content, compileOnly, engine = null) {
  const issues = [];

  if (!content.includes('\\begin{document}')) {
    issues.push('Missing \\begin{document}');
  }
  if (!content.includes('\\end{document}')) {
    issues.push('Missing \\end{document}');
  }

  if (compileOnly) {
    return { issues, counts: { resumeItems: 0, subheadings: 0, projectHeadings: 0 } };
  }

  const sectionCount = (content.match(/\\section\{/g) || []).length;
  if (sectionCount < MIN_SECTIONS) {
    issues.push(`Expected at least ${MIN_SECTIONS} \\section{} blocks (Education, Work Experience, Projects, Skills — or localized equivalents), found ${sectionCount}`);
  }

  if (CJK_RE.test(content)) {
    const xetex = engine === 'tectonic' || engine === 'xelatex';
    if (xetex && CJK_PACKAGE_RE.test(content)) {
      // XeTeX backend + xeCJK/ctex loaded: CJK renders.
    } else if (xetex) {
      issues.push('CJK characters detected but no CJK package (xeCJK/ctex) is loaded. Generate from the CJK-aware template instead: `node build-cv-latex.mjs <input.json> <output.tex> --template=cjk` (templates/cv-template.cjk.tex), or use `pdf` mode (HTML to PDF, which renders CJK) for these CVs.');
    } else {
      issues.push('CJK characters detected. This CJK-aware LaTeX path needs a XeTeX-based engine (fontspec/xeCJK) — pdfLaTeX cannot compile it. Install tectonic (brew install tectonic) and regenerate from the CJK-aware template (`--template=cjk`), or use `pdf` mode (HTML to PDF, which renders CJK) for these CVs.');
    }
  }

  for (const cmd of REQUIRED_COMMANDS) {
    if (!new RegExp(cmd).test(content)) {
      issues.push(`Missing command: ${cmd}`);
    }
  }

  const unresolvedMatch = content.match(/\{\{[A-Z_]+\}\}/g);
  if (unresolvedMatch) {
    issues.push(`Unresolved placeholders: ${[...new Set(unresolvedMatch)].join(', ')}`);
  }

  let resumeItemCount = 0;
  let subheadingCount = 0;
  let projectHeadingCount = 0;
  for (const line of content.split('\n')) {
    if (/\\resumeItem\{/.test(line)) resumeItemCount++;
    if (/\\resumeSubheading[^C]/.test(line)) subheadingCount++;
    if (/\\resumeProjectHeading/.test(line)) projectHeadingCount++;
  }

  // pdfgentounicode — pdfTeX-only primitive for ATS-compatible glyph mapping.
  // XeLaTeX (fontspec) crashes on it and already emits Unicode-mapped PDFs
  // natively via its OpenType engine, so the requirement does not apply.
  const isXeLaTeX = content.includes('\\usepackage{fontspec}');
  if (!isXeLaTeX && !content.includes('\\pdfgentounicode=1')) {
    issues.push('Missing \\pdfgentounicode=1 (ATS compatibility)');
  }

  return {
    issues,
    counts: {
      resumeItems: resumeItemCount,
      subheadings: subheadingCount,
      projectHeadings: projectHeadingCount,
    },
  };
}

async function main() {
  // Parse positional args (skip any --flag=... tokens)
  const positional = [];
  let reportFlag = null;
  let lang = 'en';
  // --project-bullets=N: raise the per-project cap for one CV (default stays 2).
  let projectBullets = MAX_PROJECT_BULLETS;
  // --compile-only: user-owned .tex (latex-tex mode) — skip template checks.
  const compileOnly = process.argv.includes('--compile-only');
  for (const arg of process.argv.slice(2)) {
    if (arg.startsWith('--report=')) {
      reportFlag = arg.slice('--report='.length);
    } else if (arg.startsWith('--lang=')) {
      lang = arg.slice('--lang='.length);
    } else if (arg.startsWith('--project-bullets=')) {
      projectBullets = Number(arg.slice('--project-bullets='.length));
      if (!Number.isInteger(projectBullets) || projectBullets < 1 || projectBullets > 5) {
        console.error('--project-bullets must be an integer from 1 to 5');
        process.exit(1);
      }
    } else if (!arg.startsWith('--')) {
      positional.push(arg);
    }
  }
  const inputPath = positional[0];
  const outputPath = positional[1]; // optional
  if (!inputPath) {
    console.error('Usage: node generate-latex.mjs <input.tex> [output.pdf] [--report=<path>] [--lang=en|it] [--project-bullets=N] [--compile-only]');
    process.exit(1);
  }

  // A mistyped --report must fail, not silently fall back to cv.md.
  if (reportFlag && !existsSync(resolve(reportFlag))) {
    console.error(`Report not found: ${reportFlag}`);
    process.exit(1);
  }

  const cvFile = CV_FILES[lang];
  if (!cvFile) {
    console.error(`Unknown --lang=${lang}. Supported: ${Object.keys(CV_FILES).join(', ')}`);
    process.exit(1);
  }
  if (!compileOnly && !existsSync(resolve(DATA_ROOT, cvFile))) {
    console.error(`${cvFile} not found in ${DATA_ROOT}: --lang=${lang} needs it`);
    process.exit(1);
  }

  const absPath = resolve(inputPath);
  let content;
  try {
    content = await readFile(absPath, 'utf-8');
  } catch (err) {
    console.error(`Error reading ${absPath}: ${err.message}`);
    process.exit(1);
  }

  // --- {{SUMMARY}} substitution (pre-validation) ---
  // Runs only if the .tex still contains the placeholder. Source chain:
  //   report "Tailored CV Summary (<lang>)" > plain one in <lang> > CV file "## Summary"
  // Mutates the input .tex in place so xelatex consumes the resolved file.
  let summarySource = null;
  if (content.includes('{{SUMMARY}}')) {
    const summary = await extractTailoredSummary({
      scriptDir: DATA_ROOT,
      reportFlag,
      lang,
      cvFile,
    });
    if (summary) {
      content = content.replace(/\{\{SUMMARY\}\}/g, () => escapeLatex(summary.text));
      // template intentionally NOT mutated; final content is compiled from a working copy (see below)
      summarySource = summary.source;
    }
  }

  // --- {{CERTIFICATIONS}} substitution (pre-validation) ---
  // Source: cv.md "## Certifications" only (no tailoring per role, no source chain).
  // Missing/empty section => empty string (template section renders title-only).
  let certificationsSource = null;
  if (content.includes('{{CERTIFICATIONS}}')) {
    let certs = [];
    try {
      const md = await readFile(resolve(DATA_ROOT, cvFile), 'utf-8');
      certs = extractCertifications(md);
      certificationsSource = certs.length ? `${cvFile}:${certs.length}` : `${cvFile}:empty`;
    } catch {
      certificationsSource = `${cvFile}:missing`;
    }
    const rendered = formatCertificationsLatex(certs);
    content = content.replace(/\{\{CERTIFICATIONS\}\}/g, () => rendered);
    // template intentionally NOT mutated; final content is compiled from a working copy (see below)
  }

  // --- {{CONTACT_LINE}} substitution (pre-validation) ---
  // Source: config/profile.yml identity block (phone + city + country).
  // Visa/work authorization is intentionally excluded (internal-only field).
  // Values are LaTeX-escaped; the "$|$" math-mode separator is preserved raw.
  let contactLineSource = null;
  if (content.includes('{{CONTACT_LINE}}')) {
    try {
      const yml = await readFile(resolve(DATA_ROOT, 'config/profile.yml'), 'utf-8');
      let line = parseContactLine(yml);
      for (const [from, to] of Object.entries(COUNTRY[lang] || {})) {
        if (line) line = line.replace(new RegExp(`, ${from}$`), `, ${to}`);
      }
      if (line) {
        content = content.replace(/\{\{CONTACT_LINE\}\}/g, () => line);
        // template intentionally NOT mutated; final content is compiled from a working copy (see below)
        contactLineSource = 'profile.yml';
      } else {
        contactLineSource = 'profile.yml:empty';
      }
    } catch {
      contactLineSource = 'profile.yml:missing';
    }
  }

  // --- Header identity placeholders (NAME, EMAIL_*, LINKEDIN_*, GITHUB_*) ---
  // Source: config/profile.yml identity block (name, email, links.linkedin,
  // links.github). URLs are inserted raw inside \href{URL}{...}; display
  // text inside the second \href argument is LaTeX-escaped. NAME is escaped.
  // headerSource: 'profile.yml' (all 4 fields), 'profile.yml:partial' (1-3),
  // 'profile.yml:missing' (file unreadable or 0 fields).
  const HEADER_PLACEHOLDERS = [
    '{{NAME}}', '{{EMAIL_URL}}', '{{EMAIL_DISPLAY}}',
    '{{LINKEDIN_URL}}', '{{LINKEDIN_DISPLAY}}',
    '{{GITHUB_URL}}', '{{GITHUB_DISPLAY}}',
  ];
  let headerSource = null;
  if (HEADER_PLACEHOLDERS.some(p => content.includes(p))) {
    try {
      const yml = await readFile(resolve(DATA_ROOT, 'config/profile.yml'), 'utf-8');
      const id = parseHeaderIdentity(yml);
      const present = [id.name, id.email, id.linkedin, id.github].filter(Boolean).length;
      if (present === 4) headerSource = 'profile.yml';
      else if (present > 0) headerSource = 'profile.yml:partial';
      else headerSource = 'profile.yml:missing';

      if (id.name) content = content.replace(/\{\{NAME\}\}/g, () => escapeLatex(id.name));
      if (id.email) {
        content = content.replace(/\{\{EMAIL_URL\}\}/g, () => id.email);
        content = content.replace(/\{\{EMAIL_DISPLAY\}\}/g, () => escapeLatex(id.email));
      }
      if (id.linkedin) {
        content = content.replace(/\{\{LINKEDIN_URL\}\}/g, () => id.linkedin);
        content = content.replace(/\{\{LINKEDIN_DISPLAY\}\}/g, () => escapeLatex(urlToDisplay(id.linkedin)));
      }
      if (id.github) {
        content = content.replace(/\{\{GITHUB_URL\}\}/g, () => id.github);
        content = content.replace(/\{\{GITHUB_DISPLAY\}\}/g, () => escapeLatex(urlToDisplay(id.github)));
      }
      // template intentionally NOT mutated; final content is compiled from a working copy (see below)
    } catch {
      headerSource = 'profile.yml:missing';
    }
  }

  // --- {{SKILLS}} substitution (cv.md "## Technical Skills") ---
  let skillsSource = null;
  if (content.includes('{{SKILLS}}')) {
    try {
      const md = await readFile(resolve(DATA_ROOT, cvFile), 'utf-8');
      const skills = extractSkills(md);
      content = content.replace(/\{\{SKILLS\}\}/g, () => formatSkillsLatex(skills));
      skillsSource = skills.length ? `${cvFile}:${skills.length}` : `${cvFile}:empty`;
    } catch {
      skillsSource = `${cvFile}:missing`;
      content = content.replace(/\{\{SKILLS\}\}/g, () => '');
    }
    // template intentionally NOT mutated; final content is compiled from a working copy (see below)
  }

  // --- {{EDUCATION}} substitution (cv.md "## Education") ---
  let educationSource = null;
  if (content.includes('{{EDUCATION}}')) {
    try {
      const md = await readFile(resolve(DATA_ROOT, cvFile), 'utf-8');
      const entries = extractEducation(md);
      content = content.replace(/\{\{EDUCATION\}\}/g, () => formatEducationLatex(entries));
      educationSource = entries.length ? `${cvFile}:${entries.length}` : `${cvFile}:empty`;
    } catch {
      educationSource = `${cvFile}:missing`;
      content = content.replace(/\{\{EDUCATION\}\}/g, () => '');
    }
    // template intentionally NOT mutated; final content is compiled from a working copy (see below)
  }

  // --- Relevance Selection: load once, shared between EXPERIENCE and PROJECTS ---
  // Same source as SUMMARY: explicit --report only.
  let relevanceSelection = { experience: [], projects: [] };
  const selectionIssues = [];
  if (content.includes('{{EXPERIENCE}}') || content.includes('{{PROJECTS}}')) {
    const reportMd = await loadReportForSelection({ scriptDir: DATA_ROOT, reportFlag });
    if (reportMd) relevanceSelection = extractRelevanceSelection(reportMd);
  }

  // --- {{EXPERIENCE}} substitution (cv.md content + optional report-driven selection) ---
  let experienceSource = null;
  let experienceSelected = null;
  if (content.includes('{{EXPERIENCE}}')) {
    try {
      const md = await readFile(resolve(DATA_ROOT, 'cv.md'), 'utf-8');
      const all = extractExperience(md);
      const out = cvFile === 'cv.md' ? all : extractExperience(await readFile(resolve(DATA_ROOT, cvFile), 'utf-8'));
      checkParity(all, out, e => e.bullets.length, 'Experience', cvFile, selectionIssues);
      all.forEach((e, i) => { e.idx = i; });
      experienceSource = all.length ? `${cvFile}:${all.length}` : `${cvFile}:empty`;
      const { ordered, info } = applySelection(all, relevanceSelection.experience, e => `${e.company} ${e.role}`);
      if (relevanceSelection.experience.length) {
        experienceSelected = `selected:${info.selected}+fallback:${info.fallback}`;
      }
      content = content.replace(/\{\{EXPERIENCE\}\}/g, () => formatExperienceLatex(ordered.map(e => {
        const picked = pickBullets(e.bullets, e.pick, b => b, MAX_EXPERIENCE_BULLETS, e.role, selectionIssues);
        const o = out[e.idx] ?? e;
        return { ...o, bullets: picked.map(b => o.bullets[e.bullets.indexOf(b)] ?? b) };
      })));
    } catch {
      experienceSource = `${cvFile}:missing`;
      content = content.replace(/\{\{EXPERIENCE\}\}/g, () => '');
    }
    // template intentionally NOT mutated; final content is compiled from a working copy (see below)
  }

  // --- {{PROJECTS}} substitution (cv.md content + optional report-driven selection, Opzione D) ---
  let projectsSource = null;
  let projectsSelected = null;
  if (content.includes('{{PROJECTS}}')) {
    try {
      const md = await readFile(resolve(DATA_ROOT, 'cv.md'), 'utf-8');
      const all = extractProjects(md);
      const out = cvFile === 'cv.md' ? all : extractProjects(await readFile(resolve(DATA_ROOT, cvFile), 'utf-8'));
      checkParity(all, out, p => p.metaBullets.length, 'Projects', cvFile, selectionIssues);
      all.forEach((p, i) => { p.idx = i; });
      projectsSource = all.length ? `${cvFile}:${all.length}` : `${cvFile}:empty`;
      const { ordered, info } = applySelection(all, relevanceSelection.projects, p => p.name);
      if (relevanceSelection.projects.length) {
        projectsSelected = `selected:${info.selected}+fallback:${info.fallback}`;
      }
      content = content.replace(/\{\{PROJECTS\}\}/g, () => formatProjectsLatex(ordered.slice(0, MAX_PROJECTS).map(p => {
        const picked = pickBullets(p.metaBullets, p.pick, mb => mb.key, projectBullets, p.name, selectionIssues);
        const o = out[p.idx] ?? p;
        return { ...o, metaBullets: picked.map(mb => o.metaBullets[p.metaBullets.indexOf(mb)] ?? mb) };
      })));
    } catch {
      projectsSource = `${cvFile}:missing`;
      content = content.replace(/\{\{PROJECTS\}\}/g, () => '');
    }
    // template intentionally NOT mutated; final content is compiled from a working copy (see below)
  }

  // Section titles and hyphenation follow the CV language; the template is
  // written once, in English.
  const titles = SECTION_TITLES[lang];
  if (titles) {
    content = content.replace(/\\section\{([^}]+)\}/g, (m, t) => (titles[t] ? `\\section{${titles[t]}}` : m));
  }
  content = content.replace(/\\usepackage\[english\]\{babel\}/, () => `\\usepackage[${BABEL[lang]}]{babel}`);

  // Engine first: the CJK check depends on it.
  const engine = resolveLatexEngine();
  const { issues, counts } = validateLatexContent(content, compileOnly, engine);
  issues.push(...selectionIssues);

  const fileInfo = await stat(absPath);
  const sizeKB = (fileInfo.size / 1024).toFixed(1);

  // Output report as JSON
  const report = {
    file: basename(absPath),
    path: absPath,
    sizeKB: parseFloat(sizeKB),
    counts,
    issues,
    valid: issues.length === 0,
    lang,
    ...(compileOnly && { compileOnly }),
    ...(summarySource && { summarySource }),
    ...(certificationsSource && { certificationsSource }),
    ...(contactLineSource && { contactLineSource }),
    ...(headerSource && { headerSource }),
    ...(skillsSource && { skillsSource }),
    ...(educationSource && { educationSource }),
    ...(experienceSource && { experienceSource }),
    ...(experienceSelected && { experienceSelected }),
    ...(projectsSource && { projectsSource }),
    ...(projectsSelected && { projectsSelected }),
  };

  // If validation fails, report and exit
  if (issues.length > 0) {
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  // --- Compile .tex → .pdf ---
  const texDir = dirname(absPath);
  const texBase = basename(absPath, '.tex');
  const defaultPdf = join(texDir, `${texBase}.pdf`);
  const targetPdf = outputPath ? resolve(outputPath) : defaultPdf;

  // Ensure output directory exists
  const targetDir = dirname(targetPdf);
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  if (!engine) {
    report.compiled = false;
    report.compileError = 'No LaTeX engine found. Install tectonic (brew install tectonic), xelatex, or pdflatex.';
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  report.engine = engine;

  // For xelatex: use -jobname to avoid PDF collisions when a viewer holds
  // the default `<tex-basename>.pdf` (e.g. an HTML pipeline output sharing the
  // same basename). Falls back to tex basename when no explicit output given.
  const jobname = basename(targetPdf, '.pdf');

  // Compile a WORKING COPY of the fully-substituted content. The input
  // template on disk is never mutated, so its {{...}} placeholders survive
  // for the next run. `content` already holds every substitution.
  let compileText = content;
  if (engine === 'tectonic') {
    // tectonic: strip pdflatex-only primitives that cause crashes
    compileText = content
      .replace(/\\pdfgentounicode\s*=\s*\d+[^\n]*\n?/g, '')
      .replace(/\\input\{glyphtounicode\}[^\n]*\n?/g, '');
  }
  const compilePath = join(texDir, `${jobname}.__work.tex`);
  await writeFile(compilePath, compileText, 'utf-8');

  try {
    if (engine === 'tectonic') {
      // Tectonic handles multi-pass automatically; --outdir sets output location
      execFileSync('tectonic', ['--outdir', texDir, compilePath], {
        cwd: texDir,
        stdio: 'pipe',
        timeout: 120_000,
      });
    } else if (engine === 'xelatex') {
      const xelatexArgs = [
        '-no-shell-escape',
        '-interaction=nonstopmode',
        '-halt-on-error',
        `-output-directory=${targetDir}`,
        `-jobname=${jobname}`,
        compilePath,
      ];
      // First pass
      execFileSync('xelatex', xelatexArgs, { cwd: texDir, stdio: 'pipe', timeout: 120_000 });
      // Second pass (resolves references)
      execFileSync('xelatex', xelatexArgs, { cwd: texDir, stdio: 'pipe', timeout: 120_000 });
    } else {
      // pdflatex
      const pdflatexArgs = [
        '-no-shell-escape',
        '-interaction=nonstopmode',
        '-halt-on-error',
        `-output-directory=${texDir}`,
        absPath,
      ];
      // First pass
      execFileSync('pdflatex', pdflatexArgs, { cwd: texDir, stdio: 'pipe', timeout: 120_000 });
      // Second pass (resolves references)
      execFileSync('pdflatex', pdflatexArgs, { cwd: texDir, stdio: 'pipe', timeout: 120_000 });
    }

    report.compiled = true;
  } catch (err) {
    // Determine log path based on engine
    let logPath;
    if (engine === 'xelatex') {
      // xelatex with -jobname writes log to targetDir/<jobname>.log
      logPath = join(targetDir, `${jobname}.log`);
    } else {
      // tectonic and pdflatex write log to texDir/<basename>.log
      const logBase = engine === 'tectonic' ? basename(compilePath, '.tex') : texBase;
      logPath = join(texDir, `${logBase}.log`);
    }
    let latexError = err.message;
    try {
      const log = await readFile(logPath, 'utf-8');
      const errorLines = log.split('\n').filter(l => l.startsWith('!'));
      if (errorLines.length > 0) {
        latexError = errorLines.join('\n');
      }
    } catch { /* no log file */ }

    report.compiled = false;
    report.compileError = latexError;
  }

  // Post-compile: locate the produced PDF, move it to targetPdf if needed,
  // stat it, and clean up auxiliary files.
  if (report.compiled) {
    // Determine where the engine wrote the PDF
    let producedPdf;
    if (engine === 'tectonic') {
      // Tectonic writes <compileBase>.pdf in texDir (compileBase = patched temp)
      const compileBase = basename(compilePath, '.tex');
      producedPdf = join(texDir, `${compileBase}.pdf`);
    } else if (engine === 'xelatex') {
      // xelatex with -jobname writes <jobname>.pdf in targetDir
      producedPdf = join(targetDir, `${jobname}.pdf`);
    } else {
      // pdflatex writes <texBase>.pdf in texDir
      producedPdf = defaultPdf;
    }

    try {
      // Move/copy the produced PDF to targetPdf if they differ
      if (resolve(producedPdf) !== resolve(targetPdf)) {
        await copyFile(producedPdf, targetPdf);
        await rm(producedPdf).catch(() => { });
      }

      const pdfStat = await stat(targetPdf);
      report.pdf = {
        path: targetPdf,
        sizeKB: parseFloat((pdfStat.size / 1024).toFixed(1)),
      };
    } catch (err) {
      report.postCompileError = `Failed to finalize output PDF: ${err.message}`;
    }

    // Clean up auxiliary files (best-effort)
    const auxExts = ['.aux', '.log', '.out', '.fls', '.fdb_latexmk', '.synctex.gz'];

    if (engine === 'xelatex') {
      // xelatex aux files are named after jobname in targetDir
      for (const ext of auxExts) {
        await rm(join(targetDir, `${jobname}${ext}`)).catch(() => { });
      }
    } else {
      // tectonic & pdflatex aux files in texDir
      const cleanupBase = engine === 'tectonic' ? basename(compilePath, '.tex') : texBase;
      for (const ext of auxExts) {
        await rm(join(texDir, `${cleanupBase}${ext}`)).catch(() => { });
      }
      // Tectonic also leaves a temp .tex — clean it
      if (engine === 'tectonic') {
        await rm(compilePath).catch(() => { });
      }
    }
  }

  console.log(JSON.stringify(report, null, 2));
  process.exit(report.compiled ? 0 : 1);
}

if (isMainModule(import.meta.url)) main();
